server:
  port: 8080
# propriedades Spring
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"