# propriedades Spring
spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
# propriedades personalizadas
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"
