
server:
  port: 8761
spring:
  application:
    name: naming-server
eureka:
  client:
    # evitando auto registro do server no ambiente de desenvolvimento
    register-with-eureka: false
    fetch-registry: false